// API Message Constants
const LOGIN = "LOGIN";
const PAGES = "DASHBOARD";
const REFDATA = "REF_DATA";
const UPLOADERACTION = "UPLOADER_ACTION";
const ASSIGNEDTASK = "ASSIGNED_TASK";
const GETASSIGNTASK = "GET_ASSIGNED_UN_ASSIGNED_TASK";
const FILTERLIST = "FILTER_LIST";
const VIEW = "VIEW";
const UPDATE = "UPDATE";
const DELETE = "DELETE";
const ADD = "ADD";
const RESETPASSWORD = "RESET_PASSWORD";
const EXUPLOAD = "EX_UPLOAD";
const LOGOUT = "LOGOUT";
const SAMPLEDOWNLOAD = "SAMPLE_FORMAT_DOWNLOAD";
const REQUESTOTP = "OTP";
const VALIDATEOTP = "RESET_PASSWORD_OTP_VALIDATION";
const FINANCIALAPP = "FINANCIAL_APP";
const ITEMSEQUENCE = "ITEM_SEQUENCE";
const SUMMARY = "DASHBOARD_SUMMARY";

export {
  LOGIN,
  PAGES,
  REFDATA,
  UPLOADERACTION,
  ASSIGNEDTASK,
  GETASSIGNTASK,
  FILTERLIST,
  VIEW,
  UPDATE,
  DELETE,
  ADD,
  RESETPASSWORD,
  EXUPLOAD,
  LOGOUT,
  SAMPLEDOWNLOAD,
  REQUESTOTP,
  VALIDATEOTP,
  FINANCIALAPP,
  ITEMSEQUENCE,
};
